# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(745, 637)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 50, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plaintext = QtWidgets.QLabel(Form)
        self.plaintext.setGeometry(QtCore.QRect(60, 100, 61, 16))
        self.plaintext.setObjectName("plaintext")
        self.key = QtWidgets.QLabel(Form)
        self.key.setGeometry(QtCore.QRect(60, 190, 61, 16))
        self.key.setObjectName("key")
        self.ciphertext = QtWidgets.QLabel(Form)
        self.ciphertext.setGeometry(QtCore.QRect(60, 260, 71, 16))
        self.ciphertext.setObjectName("ciphertext")
        self.txt_plain = QtWidgets.QPlainTextEdit(Form)
        self.txt_plain.setGeometry(QtCore.QRect(170, 100, 381, 71))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_key = QtWidgets.QPlainTextEdit(Form)
        self.txt_key.setGeometry(QtCore.QRect(170, 190, 381, 41))
        self.txt_key.setObjectName("txt_key")
        self.txt_cipher = QtWidgets.QPlainTextEdit(Form)
        self.txt_cipher.setGeometry(QtCore.QRect(170, 260, 381, 71))
        self.txt_cipher.setObjectName("txt_cipher")
        self.btn_encrypt = QtWidgets.QPushButton(Form)
        self.btn_encrypt.setGeometry(QtCore.QRect(190, 370, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(Form)
        self.btn_decrypt.setGeometry(QtCore.QRect(430, 370, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CAESAR CIPHER"))
        self.plaintext.setText(_translate("Form", "Plain Text:"))
        self.key.setText(_translate("Form", "Key:"))
        self.ciphertext.setText(_translate("Form", "CipherText:"))
        self.btn_encrypt.setText(_translate("Form", "Encrypt"))
        self.btn_decrypt.setText(_translate("Form", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
